### ISSUE TITLE
Add support of WindowsLive  codepage to ActiveSync

### ISSUE THREAD

**Issue by SBoyNumber1** [schmurfy/libwbxml#1]
Additional info from here:
 http://social.msdn.microsoft.com/Forums/en-US/75562e26-158c-45d3-b114-b2b82928c3a7/undocumented-activesync-codepage?forum=os_exchangeprotocols

**Comment by schmurfy** [comment]
Hi, from what I understand its only purpose is to connect to Hotmail which might not be that useful.

**Comment by SBoyNumber1** [comment]
As I understand from link bellow its used to provide calendar permissions.
http://msdn.microsoft.com/en-us/live/jj572363.aspx

**Comment by prepas** [comment]
Hi, I have the same problem - I can't add these tags from WindowsLive space 
http://social.msdn.microsoft.com/Forums/en-US/75562e26-158c-45d3-b114-b2b82928c3a7/undocumented-activesync-codepage?forum=os_exchangeprotocols
